// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SimpleOpenBadge/authentication-api/internal/factories/auth/signup/lambda (interfaces: SignUpLambdaFactory)

// Package mockedSignUpFactory is a generated GoMock package.
package mockedSignUpFactory

import (
	context "context"
	reflect "reflect"

	events "github.com/aws/aws-lambda-go/events"
	gomock "github.com/golang/mock/gomock"
)

// MockSignUpLambdaFactory is a mock of SignUpLambdaFactory interface.
type MockSignUpLambdaFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSignUpLambdaFactoryMockRecorder
}

// MockSignUpLambdaFactoryMockRecorder is the mock recorder for MockSignUpLambdaFactory.
type MockSignUpLambdaFactoryMockRecorder struct {
	mock *MockSignUpLambdaFactory
}

// NewMockSignUpLambdaFactory creates a new mock instance.
func NewMockSignUpLambdaFactory(ctrl *gomock.Controller) *MockSignUpLambdaFactory {
	mock := &MockSignUpLambdaFactory{ctrl: ctrl}
	mock.recorder = &MockSignUpLambdaFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignUpLambdaFactory) EXPECT() *MockSignUpLambdaFactoryMockRecorder {
	return m.recorder
}

// Handler mocks base method.
func (m *MockSignUpLambdaFactory) Handler(arg0 context.Context, arg1 events.APIGatewayProxyRequest) (*events.APIGatewayProxyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handler", arg0, arg1)
	ret0, _ := ret[0].(*events.APIGatewayProxyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handler indicates an expected call of Handler.
func (mr *MockSignUpLambdaFactoryMockRecorder) Handler(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handler", reflect.TypeOf((*MockSignUpLambdaFactory)(nil).Handler), arg0, arg1)
}

// Start mocks base method.
func (m *MockSignUpLambdaFactory) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockSignUpLambdaFactoryMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSignUpLambdaFactory)(nil).Start))
}
